#!/bin/sh

BFLAGS=-B../../../../../../../build/gcc/stage1/gm2
CLIBS=-I../../../../gm2-iso:.:/usr/local/lib/gcc-lib/i686-pc-linux-gnu/3.2/gm2/iso:/usr/local/lib/gcc-lib/i686-pc-linux-gnu/3.2/gm2/pim
LLIBS=-I.:/usr/local/lib/gcc-lib/i686-pc-linux-gnu/3.2/gm2/iso:/usr/local/lib/gcc-lib/i686-pc-linux-gnu/3.2/gm2/pim
DRIVER=../../../../../../../build/gcc/xgm2
OPTS=-Wiso $2
CPP=

if [ ! -x $DRIVER ] ; then
   echo "cannot find $DRIVER"
   exit 1
fi
if ! $DRIVER $OPTS $BFLAGS $CLIBS -gstabs -c $1 ; then
    exit $?
fi
if ! $DRIVER $OPTS $BFLAGS $CLIBS -S -gstabs -c $1 ; then
    exit $?
fi
if ! $DRIVER $OPTS $BFLAGS $LLIBS -gstabs -I. $1 -lm ; then
    exit $?
fi
cat << EOFEOF > .gdbinit
# set language modula-2
# set language pascal
break _M2_`basename $1 .mod`_init
run
#next
#print r
#ptype r
EOFEOF
emacs .gdbinit

