#!/bin/sh

source config-values
source shell-bin/libs

cd ${DOWNLOADDIR}

#
#  check gcc version and match the CVS branch
#

case ${GCC} in
  3.3.? )  CVSARGS="-D 20060623" ;;
  4.1.? )  CVSARGS="" ;;
  *     )  echo "it is unlikely that GNU Modula-2 will work with gcc-${GCC}" ;;
esac


if [ "${FORCECVS}" = "yes" ] ; then
   rm -rf gm2 testsuite gm2-current.tar.gz
   checkok "cvs -d ${CVSROOT} checkout ${CVSARGS} gm2 testsuite" "cvs checkout"
else
   if [ ! -d gm2 ] ; then
      checkok "cvs -d ${CVSROOT} checkout ${CVSARGS} gm2" "cvs checkout of the compiler"
   fi
   if [ ! -d testsuite ] ; then
      checkok "cvs -d ${CVSROOT} checkout ${CVSARGS} testsuite" "cvs checkout of the testsuite"
   fi
fi


#
# fix any incorrect time stamps
#

find gm2 testsuite -exec touch {} \;
tar zcf gm2-current.tar.gz gm2 testsuite
cd ..
