#!/bin/sh

source config-values

if [ -d ${BUILDDIR} ] ; then
   rm -rf ${BUILDDIR}
fi

if [ ! -d ${PREFIX} ] ; then
    mkdir ${PREFIX}
fi

echo "building bootstrap C compiler"
mkdir ${BUILDDIR}
cd ${BUILDDIR}
../${SOURCEDIR}/gcc-${GCC}/configure --enable-languages=c --disable-multilib --prefix=${PREFIX}
time make
make install
cd ..

PATH=${PREFIX}/bin:$PATH
export PATH
echo "PATH = $PATH"

ULMLIB="yes"
if [ "$1" = "no" ] ; then
   ULMLIB="no"
fi
export ULMLIB

echo "building C and Modula-2 compilers"
cd ${BUILDDIR}
../${SOURCEDIR}/gcc-${GCC}/configure --enable-languages=c,gm2 --disable-multilib --prefix=${PREFIX}
time make
cd ..
