extern "C" void exit(int);

extern "C" void RTExceptions_DefaultErrorCatch(void);
extern "C" void _M2_Storage_init (int argc, char *argv[]);
extern "C" void _M2_Storage_finish (void);
extern "C" void _M2_SYSTEM_init (int argc, char *argv[]);
extern "C" void _M2_SYSTEM_finish (void);
extern "C" void _M2_M2RTS_init (int argc, char *argv[]);
extern "C" void _M2_M2RTS_finish (void);
extern "C" void _M2_RTExceptions_init (int argc, char *argv[]);
extern "C" void _M2_RTExceptions_finish (void);
extern "C" void _M2_IOLink_init (int argc, char *argv[]);
extern "C" void _M2_IOLink_finish (void);
extern "C" void _M2_SysExceptions_init (int argc, char *argv[]);
extern "C" void _M2_SysExceptions_finish (void);
extern "C" void _M2_RTgenif_init (int argc, char *argv[]);
extern "C" void _M2_RTgenif_finish (void);
extern "C" void _M2_ErrnoCategory_init (int argc, char *argv[]);
extern "C" void _M2_ErrnoCategory_finish (void);
extern "C" void _M2_Indexing_init (int argc, char *argv[]);
extern "C" void _M2_Indexing_finish (void);
extern "C" void _M2_RTgen_init (int argc, char *argv[]);
extern "C" void _M2_RTgen_finish (void);
extern "C" void _M2_RTfio_init (int argc, char *argv[]);
extern "C" void _M2_RTfio_finish (void);
extern "C" void _M2_NumberIO_init (int argc, char *argv[]);
extern "C" void _M2_NumberIO_finish (void);
extern "C" void _M2_ASCII_init (int argc, char *argv[]);
extern "C" void _M2_ASCII_finish (void);
extern "C" void _M2_EXCEPTIONS_init (int argc, char *argv[]);
extern "C" void _M2_EXCEPTIONS_finish (void);
extern "C" void _M2_ldtoa_init (int argc, char *argv[]);
extern "C" void _M2_ldtoa_finish (void);
extern "C" void _M2_StdChans_init (int argc, char *argv[]);
extern "C" void _M2_StdChans_finish (void);
extern "C" void _M2_M2EXCEPTION_init (int argc, char *argv[]);
extern "C" void _M2_M2EXCEPTION_finish (void);
extern "C" void _M2_StrLib_init (int argc, char *argv[]);
extern "C" void _M2_StrLib_finish (void);
extern "C" void _M2_FIO_init (int argc, char *argv[]);
extern "C" void _M2_FIO_finish (void);
extern "C" void _M2_errno_init (int argc, char *argv[]);
extern "C" void _M2_errno_finish (void);
extern "C" void _M2_RTio_init (int argc, char *argv[]);
extern "C" void _M2_RTio_finish (void);
extern "C" void _M2_CharClass_init (int argc, char *argv[]);
extern "C" void _M2_CharClass_finish (void);
extern "C" void _M2_ConvTypes_init (int argc, char *argv[]);
extern "C" void _M2_ConvTypes_finish (void);
extern "C" void _M2_termios_init (int argc, char *argv[]);
extern "C" void _M2_termios_finish (void);
extern "C" void _M2_StringConvert_init (int argc, char *argv[]);
extern "C" void _M2_StringConvert_finish (void);
extern "C" void _M2_dtoa_init (int argc, char *argv[]);
extern "C" void _M2_dtoa_finish (void);
extern "C" void _M2_IOConsts_init (int argc, char *argv[]);
extern "C" void _M2_IOConsts_finish (void);
extern "C" void _M2_DynamicStrings_init (int argc, char *argv[]);
extern "C" void _M2_DynamicStrings_finish (void);
extern "C" void _M2_IOChan_init (int argc, char *argv[]);
extern "C" void _M2_IOChan_finish (void);
extern "C" void _M2_ChanConsts_init (int argc, char *argv[]);
extern "C" void _M2_ChanConsts_finish (void);
extern "C" void _M2_ConvStringReal_init (int argc, char *argv[]);
extern "C" void _M2_ConvStringReal_finish (void);
extern "C" void _M2_WholeConv_init (int argc, char *argv[]);
extern "C" void _M2_WholeConv_finish (void);
extern "C" void _M2_IO_init (int argc, char *argv[]);
extern "C" void _M2_IO_finish (void);
extern "C" void _M2_RTentity_init (int argc, char *argv[]);
extern "C" void _M2_RTentity_finish (void);
extern "C" void _M2_TextIO_init (int argc, char *argv[]);
extern "C" void _M2_TextIO_finish (void);
extern "C" void _M2_Selective_init (int argc, char *argv[]);
extern "C" void _M2_Selective_finish (void);
extern "C" void _M2_RealConv_init (int argc, char *argv[]);
extern "C" void _M2_RealConv_finish (void);
extern "C" void _M2_RTdata_init (int argc, char *argv[]);
extern "C" void _M2_RTdata_finish (void);
extern "C" void _M2_Strings_init (int argc, char *argv[]);
extern "C" void _M2_Strings_finish (void);
extern "C" void _M2_WholeStr_init (int argc, char *argv[]);
extern "C" void _M2_WholeStr_finish (void);
extern "C" void _M2_wrapsock_init (int argc, char *argv[]);
extern "C" void _M2_wrapsock_finish (void);
extern "C" void _M2_RawIO_init (int argc, char *argv[]);
extern "C" void _M2_RawIO_finish (void);
extern "C" void _M2_StdIO_init (int argc, char *argv[]);
extern "C" void _M2_StdIO_finish (void);
extern "C" void _M2_SeqFile_init (int argc, char *argv[]);
extern "C" void _M2_SeqFile_finish (void);
extern "C" void _M2_GC_init (int argc, char *argv[]);
extern "C" void _M2_GC_finish (void);
extern "C" void _M2_delay_init (int argc, char *argv[]);
extern "C" void _M2_delay_finish (void);
extern "C" void _M2_RealIO_init (int argc, char *argv[]);
extern "C" void _M2_RealIO_finish (void);
extern "C" void _M2_ClientSocket_init (int argc, char *argv[]);
extern "C" void _M2_ClientSocket_finish (void);
extern "C" void _M2_rpc_init (int argc, char *argv[]);
extern "C" void _M2_rpc_finish (void);
extern "C" void _M2_StrIO_init (int argc, char *argv[]);
extern "C" void _M2_StrIO_finish (void);
extern "C" void _M2_Assertion_init (int argc, char *argv[]);
extern "C" void _M2_Assertion_finish (void);
extern "C" void _M2_ComplexMath_init (int argc, char *argv[]);
extern "C" void _M2_ComplexMath_finish (void);
extern "C" void _M2_StringChan_init (int argc, char *argv[]);
extern "C" void _M2_StringChan_finish (void);
extern "C" void _M2_FormatStrings_init (int argc, char *argv[]);
extern "C" void _M2_FormatStrings_finish (void);
extern "C" void _M2_devicePy_init (int argc, char *argv[]);
extern "C" void _M2_devicePy_finish (void);
extern "C" void _M2_roots_init (int argc, char *argv[]);
extern "C" void _M2_roots_finish (void);
extern "C" void _M2_Points_init (int argc, char *argv[]);
extern "C" void _M2_Points_finish (void);
extern "C" void _M2_PolyMatrix3D_init (int argc, char *argv[]);
extern "C" void _M2_PolyMatrix3D_finish (void);
extern "C" void _M2_coord_init (int argc, char *argv[]);
extern "C" void _M2_coord_finish (void);
extern "C" void _M2_Fractions_init (int argc, char *argv[]);
extern "C" void _M2_Fractions_finish (void);
extern "C" void _M2_WholeIO_init (int argc, char *argv[]);
extern "C" void _M2_WholeIO_finish (void);
extern "C" void _M2_MathLib0_init (int argc, char *argv[]);
extern "C" void _M2_MathLib0_finish (void);
extern "C" void _M2_polar_init (int argc, char *argv[]);
extern "C" void _M2_polar_finish (void);
extern "C" void _M2_history_init (int argc, char *argv[]);
extern "C" void _M2_history_finish (void);
extern "C" void _M2_deviceGroff_init (int argc, char *argv[]);
extern "C" void _M2_deviceGroff_finish (void);
extern "C" void _M2_deviceIf_init (int argc, char *argv[]);
extern "C" void _M2_deviceIf_finish (void);
extern "C" void _M2_STextIO_init (int argc, char *argv[]);
extern "C" void _M2_STextIO_finish (void);
extern "C" void _M2_SWholeIO_init (int argc, char *argv[]);
extern "C" void _M2_SWholeIO_finish (void);
extern "C" void _M2_Transform3D_init (int argc, char *argv[]);
extern "C" void _M2_Transform3D_finish (void);
extern "C" void _M2_twoDsim_init (int argc, char *argv[]);
extern "C" void _M2_twoDsim_finish (void);
extern "C" void _M2_macroObjects_init (int argc, char *argv[]);
extern "C" void _M2_macroObjects_finish (void);
extern "C" void _M2_popWorld_init (int argc, char *argv[]);
extern "C" void _M2_popWorld_finish (void);
extern "C" void _M2_bagatelle_init (int argc, char *argv[]);
extern "C" void _M2_bagatelle_finish (void);

extern "C" void M2RTS_ExecuteTerminationProcedures(void);

extern "C" void M2RTS_ExecuteInitialProcedures(void);

static void init (int argc, char *argv[])
{
   try {
       _M2_Storage_init (argc, argv);
       _M2_SYSTEM_init (argc, argv);
       _M2_M2RTS_init (argc, argv);
       _M2_RTExceptions_init (argc, argv);
       _M2_IOLink_init (argc, argv);
       _M2_SysExceptions_init (argc, argv);
       _M2_RTgenif_init (argc, argv);
       _M2_ErrnoCategory_init (argc, argv);
       _M2_Indexing_init (argc, argv);
       _M2_RTgen_init (argc, argv);
       _M2_RTfio_init (argc, argv);
       _M2_NumberIO_init (argc, argv);
       _M2_ASCII_init (argc, argv);
       _M2_EXCEPTIONS_init (argc, argv);
       _M2_ldtoa_init (argc, argv);
       _M2_StdChans_init (argc, argv);
       _M2_M2EXCEPTION_init (argc, argv);
       _M2_StrLib_init (argc, argv);
       _M2_FIO_init (argc, argv);
       _M2_errno_init (argc, argv);
       _M2_RTio_init (argc, argv);
       _M2_CharClass_init (argc, argv);
       _M2_ConvTypes_init (argc, argv);
       _M2_termios_init (argc, argv);
       _M2_StringConvert_init (argc, argv);
       _M2_dtoa_init (argc, argv);
       _M2_IOConsts_init (argc, argv);
       _M2_DynamicStrings_init (argc, argv);
       _M2_IOChan_init (argc, argv);
       _M2_ChanConsts_init (argc, argv);
       _M2_ConvStringReal_init (argc, argv);
       _M2_WholeConv_init (argc, argv);
       _M2_IO_init (argc, argv);
       _M2_RTentity_init (argc, argv);
       _M2_TextIO_init (argc, argv);
       _M2_Selective_init (argc, argv);
       _M2_RealConv_init (argc, argv);
       _M2_RTdata_init (argc, argv);
       _M2_Strings_init (argc, argv);
       _M2_WholeStr_init (argc, argv);
       _M2_wrapsock_init (argc, argv);
       _M2_RawIO_init (argc, argv);
       _M2_StdIO_init (argc, argv);
       _M2_SeqFile_init (argc, argv);
       _M2_GC_init (argc, argv);
       _M2_delay_init (argc, argv);
       _M2_RealIO_init (argc, argv);
       _M2_ClientSocket_init (argc, argv);
       _M2_rpc_init (argc, argv);
       _M2_StrIO_init (argc, argv);
       _M2_Assertion_init (argc, argv);
       _M2_ComplexMath_init (argc, argv);
       _M2_StringChan_init (argc, argv);
       _M2_FormatStrings_init (argc, argv);
       _M2_devicePy_init (argc, argv);
       _M2_roots_init (argc, argv);
       _M2_Points_init (argc, argv);
       _M2_PolyMatrix3D_init (argc, argv);
       _M2_coord_init (argc, argv);
       _M2_Fractions_init (argc, argv);
       _M2_WholeIO_init (argc, argv);
       _M2_MathLib0_init (argc, argv);
       _M2_polar_init (argc, argv);
       _M2_history_init (argc, argv);
       _M2_deviceGroff_init (argc, argv);
       _M2_deviceIf_init (argc, argv);
       _M2_STextIO_init (argc, argv);
       _M2_SWholeIO_init (argc, argv);
       _M2_Transform3D_init (argc, argv);
       _M2_twoDsim_init (argc, argv);
       _M2_macroObjects_init (argc, argv);
       _M2_popWorld_init (argc, argv);
      M2RTS_ExecuteInitialProcedures ();
       _M2_bagatelle_init (argc, argv);
    }
    catch (...) {
       RTExceptions_DefaultErrorCatch();
    }
}

static void finish (void)
{
   try {
      M2RTS_ExecuteTerminationProcedures ();
      _M2_bagatelle_finish ();
      _M2_popWorld_finish ();
      _M2_macroObjects_finish ();
      _M2_twoDsim_finish ();
      _M2_Transform3D_finish ();
      _M2_SWholeIO_finish ();
      _M2_STextIO_finish ();
      _M2_deviceIf_finish ();
      _M2_deviceGroff_finish ();
      _M2_history_finish ();
      _M2_polar_finish ();
      _M2_MathLib0_finish ();
      _M2_WholeIO_finish ();
      _M2_Fractions_finish ();
      _M2_coord_finish ();
      _M2_PolyMatrix3D_finish ();
      _M2_Points_finish ();
      _M2_roots_finish ();
      _M2_devicePy_finish ();
      _M2_FormatStrings_finish ();
      _M2_StringChan_finish ();
      _M2_ComplexMath_finish ();
      _M2_Assertion_finish ();
      _M2_StrIO_finish ();
      _M2_rpc_finish ();
      _M2_ClientSocket_finish ();
      _M2_RealIO_finish ();
      _M2_delay_finish ();
      _M2_GC_finish ();
      _M2_SeqFile_finish ();
      _M2_StdIO_finish ();
      _M2_RawIO_finish ();
      _M2_wrapsock_finish ();
      _M2_WholeStr_finish ();
      _M2_Strings_finish ();
      _M2_RTdata_finish ();
      _M2_RealConv_finish ();
      _M2_Selective_finish ();
      _M2_TextIO_finish ();
      _M2_RTentity_finish ();
      _M2_IO_finish ();
      _M2_WholeConv_finish ();
      _M2_ConvStringReal_finish ();
      _M2_ChanConsts_finish ();
      _M2_IOChan_finish ();
      _M2_DynamicStrings_finish ();
      _M2_IOConsts_finish ();
      _M2_dtoa_finish ();
      _M2_StringConvert_finish ();
      _M2_termios_finish ();
      _M2_ConvTypes_finish ();
      _M2_CharClass_finish ();
      _M2_RTio_finish ();
      _M2_errno_finish ();
      _M2_FIO_finish ();
      _M2_StrLib_finish ();
      _M2_M2EXCEPTION_finish ();
      _M2_StdChans_finish ();
      _M2_ldtoa_finish ();
      _M2_EXCEPTIONS_finish ();
      _M2_ASCII_finish ();
      _M2_NumberIO_finish ();
      _M2_RTfio_finish ();
      _M2_RTgen_finish ();
      _M2_Indexing_finish ();
      _M2_ErrnoCategory_finish ();
      _M2_RTgenif_finish ();
      _M2_SysExceptions_finish ();
      _M2_IOLink_finish ();
      _M2_RTExceptions_finish ();
      _M2_M2RTS_finish ();
      _M2_SYSTEM_finish ();
      _M2_Storage_finish ();
      exit (0);
    }
    catch (...) {
       RTExceptions_DefaultErrorCatch();
    }
}

int main (int argc, char *argv[])
{
   init (argc, argv);
   finish ();
   return (0);
}
