#!/bin/sh

if [ "$1" = "" ] ; then
   echo "debug modulename"
   exit 1
fi
if [ "$2" = "" ] ; then
   G=""
else
   G=$2
fi
if ! gm2 -g $G -c $1.mod ; then
   echo "compilation failed"
   exit 1
fi
if ! gm2 -g $G $1.mod ; then
   echo "link failed"
   exit 1
fi
cat << EOFEOF > .gdbinit
break _M2_$1_init
run
EOFEOF
emacs .gdbinit

