#!/bin/sh

export PATH=$HOME/bin/bin:$PATH


doStabs () {
    echo "====================================================="
    echo "Stabs $1"
    gm2 -g -c -gstabs+ $1.mod
    gm2 -g -gstabs+ -o a.stabs $1.mod
    if ! gdb ./a.stabs ; then
       echo "gdb crashed on $1.mod"
    fi
}


doDwarf2 () {
    echo "====================================================="
    echo "Dwarf2 $1"
    gm2 -g -c -gdwarf-2 $1.mod
    gm2 -g -gdwarf-2 -o a.dwarf2 $1.mod
    if ! gdb ./a.dwarf2 ; then
       echo "gdb crashed on $1.mod"
    fi
}


doTry () {
   cat <<EOF > .gdbinit
set lang modula-2
break _M2_$1_init
run
next
print s
ptype s
quit
EOF
   doStabs $1
   doDwarf2 $1
}

doTry setchar3
doTry subrange15
doTry subrange16
doTry subrange17
doTry array4
doTry array5
doTry char
doTry int
doTry ptrarray
doTry variant9
doTry setenum
doTry record7
doTry setchar4

type gdb
