/* do not edit automatically generated by mc from Assertion.  */
/* Assertion.mod provides an assert procedure.

Copyright (C) 2001-2020 Free Software Foundation, Inc.
Contributed by Gaius Mulley <gaius.mulley@southwales.ac.uk>.

This file is part of GNU Modula-2.

GNU Modula-2 is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

GNU Modula-2 is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with GNU Modula-2; see the file COPYING3.  If not see
<http://www.gnu.org/licenses/>.  */

#   if !defined (PROC_D)
#      define PROC_D
       typedef void (*PROC_t) (void);
       typedef struct { PROC_t proc; } PROC;
#   endif

#define _Assertion_H
#define _Assertion_C

#   include "GStrIO.h"
#   include "GM2RTS.h"


/*
   Assert - tests the boolean Condition, if it fails then HALT is called.
*/

void Assertion_Assert (unsigned int Condition);


/*
   Assert - tests the boolean Condition, if it fails then HALT is called.
*/

void Assertion_Assert (unsigned int Condition)
{
  if (! Condition)
    {
      StrIO_WriteString ((char *) "assert failed - halting system", 30);
      StrIO_WriteLn ();
      M2RTS_HALT (-1);
    }
}

void _M2_Assertion_init (__attribute__((unused)) int argc, __attribute__((unused)) char *argv[])
{
}

void _M2_Assertion_finish (__attribute__((unused)) int argc, __attribute__((unused)) char *argv[])
{
}
