/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /sources/gm2/gm2/gm2-compiler/Attic/m2lex.c,v 1.3 2002/12/20 10:43:15 gaius Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and canxrealloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 114
#define YY_END_OF_BUFFER 115
static yyconst short int yy_accept[324] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       20,   20,  115,  113,  112,   25,   57,   48,   35,   46,
       39,   40,   32,   30,   37,   31,   36,   33,  108,   56,
       38,   49,   47,   50,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,   41,   42,   43,  107,   44,   58,
       45,   59,   12,    6,    5,    6,    6,    6,    7,   10,
        7,    7,   17,   16,   14,   17,   18,  114,   19,   20,
       21,  114,  114,  112,   24,   13,    0,   27,   26,    0,
       29,   28,    1,   54,  106,    0,  108,    0,  109,  110,

      111,   34,   52,   51,   53,  107,  107,  107,  107,  107,
      107,  107,   63,  107,  107,  107,  107,   68,  107,  107,
      107,  107,  107,   76,  107,   79,  107,  107,  107,   84,
       85,  107,  107,  107,  107,  107,  107,   95,  107,  107,
      107,  107,  107,  107,  107,   12,    5,    3,    2,    4,
       10,   11,    9,    0,   14,    0,   15,    0,   18,   19,
        0,   20,    0,   23,    0,   22,   24,   13,   55,    0,
       60,  107,  101,  107,  107,  107,  107,   67,  107,   71,
      107,  107,   74,  107,  107,  107,   81,   83,  107,  107,
      107,  107,  107,  107,   93,  107,  107,  107,  107,   98,

      107,  107,  107,  107,  107,  107,    0,    0,  106,  107,
      107,   64,  107,  107,   69,  107,   72,  107,   75,  107,
      107,   80,  107,  107,  107,  107,  107,  107,  107,   94,
       96,  107,  107,  107,  107,  100,  107,  107,  107,    0,
       61,   62,   65,  107,   70,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,   97,  107,   99,  107,
      107,  107,    0,  107,   73,  107,   78,   82,  107,  107,
      107,   90,   91,   92,  107,  107,  107,  107,  107,    0,
      107,  107,   86,  107,  107,  107,  107,  107,  107,  107,
        0,  107,  107,  107,  107,  107,  102,  103,  105,  104,

        0,  107,  107,   87,   88,  107,    0,   66,  107,  107,
        0,  107,   89,    0,  107,    0,  107,    0,   77,    0,
        0,    8,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    6,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       16,   16,   16,   16,   16,   16,   16,   19,   20,   21,
       22,   23,    1,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   33,
       48,    1,   49,   50,   51,    1,   33,   33,   33,   33,

       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   52,   53,   54,   55,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[56] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    1,
        3,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[340] =
    {   0,
        0,  465,   53,   54,   55,   56,   65,   68,   73,   84,
       87,   89,  469,  471,  466,  462,   90,  471,  471,   92,
      456,  471,  471,  471,  471,  471,   84,  471,   94,  443,
      471,   74,  471,  442,  110,  130,  138,  132,  146,  148,
      177,   80,  426,  425,  424,   38,   32,  417,  431,  430,
      160,  421,   93,   82,  471,  471,  471,  405,  471,  471,
      471,  471,    0,  471,    0,  445,  445,  443,  471,    0,
      158,  410,  471,  471,  449,  194,  446,  471,  445,  446,
      471,  129,  197,  445,    0,    0,  212,  471,  471,  126,
      471,  471,  471,  432,  201,  204,    0,  414,  413,  412,

      471,  471,  471,  471,  471,  195,    0,    0,  415,  401,
      405,  196,    0,  194,  403,  202,  394,    0,  396,  409,
      127,  395,  397,    0,  395,    0,  395,  404,  388,    0,
        0,  397,  391,  403,  199,  384,  397,    0,  386,  197,
      383,  388,  389,  378,  217,    0,    0,  471,  471,  471,
        0,  471,  471,  377,  416,  243,  471,  246,  413,  412,
      411,  412,  250,  471,  252,  471,    0,    0,  471,  254,
        0,  389,    0,  380,  383,  369,  229,    0,  228,    0,
      367,  371,    0,  372,  239,  368,  362,    0,  368,  377,
      368,  364,  372,  356,    0,  362,  369,  353,  363,    0,

      370,  359,  361,  367,  358,  357,  348,  261,  264,  340,
      350,    0,  343,  348,    0,  354,    0,  342,    0,  353,
      340,    0,  345,  336,  349,  344,  335,  350,  333,    0,
        0,  348,  337,  328,  341,    0,  326,  333,  330,  333,
        0,    0,    0,  332,    0,  321,  327,  319,  332,  331,
      331,  328,  329,  313,  318,  319,    0,  320,    0,  323,
      322,  321,  323,  305,    0,  318,    0,    0,  305,  301,
      311,    0,    0,    0,  310,  307,  289,  288,  287,  294,
      304,  299,    0,  294,  305,  303,  303,  279,  278,  277,
      284,  286,  278,  289,  287,  279,    0,    0,    0,    0,

      280,  239,  250,    0,    0,  241,  217,    0,  217,  231,
      206,  208,    0,  177,  153,  140,  140,  122,    0,   96,
       76,  471,  471,  282,  285,  288,  291,  294,  297,  300,
      303,  306,  309,  312,  315,  318,  321,  324,   57
    } ;

static yyconst short int yy_def[340] =
    {   0,
      323,    1,  324,  324,  325,  325,  326,  326,  327,  327,
      328,  328,  323,  323,  323,  329,  330,  323,  323,  331,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,   35,   35,   35,   35,   35,
       38,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,  323,  323,  323,   41,  323,  323,
      323,  323,  332,  323,  333,  323,  323,  323,  323,  334,
      323,  323,  323,  323,  323,  323,  335,  323,  336,  323,
      323,  323,  323,  323,  337,  338,  330,  323,  323,  331,
      323,  323,  323,  323,  323,  323,   29,  339,  339,  339,

      323,  323,  323,  323,  323,   38,   41,   41,   41,   41,
       41,   38,   41,   35,   41,   35,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,  332,  333,  323,  323,  323,
      334,  323,  323,  323,  323,  323,  323,  323,  335,  336,
      336,  323,  323,  323,  323,  323,  337,  338,  323,  323,
       41,   41,   41,   41,   41,   41,   38,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,

       41,   41,   41,   41,   41,   41,  323,  323,  323,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,  323,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,  323,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,  323,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
      323,   41,   41,   41,   41,   41,   41,   41,   41,   41,

      323,   41,   41,   41,   41,   41,  323,   41,   41,   41,
      323,   41,   41,  323,   41,  323,   41,  323,   41,  323,
      323,  323,    0,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323
    } ;

static yyconst short int yy_nxt[527] =
    {   0,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   29,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       41,   42,   41,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   52,   53,   54,   41,   41,   55,   56,   57,
       58,   59,   60,   61,   62,   65,   65,   70,   70,   98,
       66,   66,   67,   67,   71,   71,  130,   74,  132,   75,
       74,  133,   75,   68,   68,   78,   79,  131,   72,   72,
       76,   76,   76,   76,   76,   76,   78,   79,   80,   81,
       80,   81,   88,   89,   91,  103,  104,   94,   92,   95,

       95,   95,  322,   82,   83,   82,   83,   96,  124,   97,
       97,   97,  143,  144,  125,  126,  141,   98,   99,  100,
       98,   98,   98,  321,  101,  106,  106,  106,   91,  142,
      163,  164,   92,  106,  106,  106,  106,  106,  106,  107,
      108,  107,  107,  107,  107,  109,  107,  107,  107,  110,
      111,  107,  107,  107,  107,  107,  107,  112,  181,  116,
      107,  114,  320,  117,  182,  107,  152,  107,  118,  107,
      107,  107,  107,  107,  115,  319,  113,  107,  107,  119,
      153,  120,  318,  107,  122,  107,  107,  123,  107,  317,
      137,  121,  107,  107,  107,  156,  138,  157,  165,  166,

      107,  107,  107,  107,  107,  107,  139,  107,  107,  158,
      158,  158,  316,  107,   88,   89,   95,   95,   95,   95,
       95,   95,  106,  106,  192,  174,  107,  107,  170,  107,
      177,  107,  107,  107,  175,  198,  193,  107,  199,  315,
      194,  107,  107,  204,  156,  205,  157,  156,  314,  157,
      206,  163,  164,  165,  166,  215,  106,  313,  312,  216,
      214,  158,  158,  158,  208,  107,  208,  311,  310,  209,
      209,  209,  220,  309,  308,  221,  209,  209,  209,  209,
      209,  209,   64,   64,   64,   69,   69,   69,   73,   73,
       73,   77,   77,   77,   78,   78,   78,   85,   85,   85,

       87,   87,   87,   90,   90,   90,  146,  307,  146,  147,
      306,  147,  151,  305,  151,  159,  304,  159,  161,  303,
      161,  167,  302,  167,  168,  301,  168,  300,  299,  298,
      297,  296,  295,  294,  293,  292,  291,  290,  289,  288,
      287,  286,  285,  284,  283,  282,  281,  280,  279,  278,
      277,  276,  275,  274,  273,  272,  271,  270,  269,  268,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  258,
      257,  256,  255,  254,  253,  252,  251,  250,  249,  248,
      247,  246,  245,  244,  243,  242,  241,  240,  239,  238,
      237,  236,  235,  234,  233,  232,  231,  230,  229,  228,

      227,  226,  225,  224,  223,  222,  219,  218,  217,  213,
      212,  211,  210,  162,  160,  160,  160,  155,  207,  203,
      202,  201,  200,  197,  196,  195,  191,  190,  189,  188,
      187,  186,  185,  184,  183,  180,  179,  178,  176,  173,
      172,  171,  101,  101,  101,  169,   84,  162,  160,  160,
      155,  154,  150,  149,  148,  145,  140,  136,  135,  134,
      129,  128,  127,  105,  102,   93,   86,   84,  323,   63,
       13,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,

      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323
    } ;

static yyconst short int yy_chk[527] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    5,    6,  339,
        3,    4,    3,    4,    5,    6,   46,    7,   47,    7,
        8,   47,    8,    3,    4,    9,    9,   46,    5,    6,
        7,    7,    7,    8,    8,    8,   10,   10,   11,   11,
       12,   12,   17,   17,   20,   32,   32,   27,   20,   27,

       27,   27,  321,   11,   11,   12,   12,   29,   42,   29,
       29,   29,   54,   54,   42,   42,   53,   29,   29,   29,
       29,   29,   29,  320,   29,   35,   35,   35,   90,   53,
       82,   82,   90,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   36,  121,   38,
       35,   37,  318,   38,  121,   36,   71,   38,   38,   36,
       36,   38,   38,   37,   37,  317,   36,   37,   37,   39,
       71,   39,  316,   40,   40,   39,   39,   40,   40,  315,
       51,   39,   41,   41,   41,   76,   51,   76,   83,   83,

       41,   41,   41,   41,   41,   41,   51,   41,   41,   76,
       76,   76,  314,   41,   87,   87,   95,   95,   95,   96,
       96,   96,  106,  112,  135,  112,  106,  112,   95,  114,
      116,  106,  112,  114,  114,  140,  135,  116,  140,  312,
      135,  116,  116,  145,  156,  145,  156,  158,  311,  158,
      145,  163,  163,  165,  165,  179,  177,  310,  309,  179,
      177,  158,  158,  158,  170,  177,  170,  307,  306,  170,
      170,  170,  185,  303,  302,  185,  208,  208,  208,  209,
      209,  209,  324,  324,  324,  325,  325,  325,  326,  326,
      326,  327,  327,  327,  328,  328,  328,  329,  329,  329,

      330,  330,  330,  331,  331,  331,  332,  301,  332,  333,
      296,  333,  334,  295,  334,  335,  294,  335,  336,  293,
      336,  337,  292,  337,  338,  291,  338,  290,  289,  288,
      287,  286,  285,  284,  282,  281,  280,  279,  278,  277,
      276,  275,  271,  270,  269,  266,  264,  263,  262,  261,
      260,  258,  256,  255,  254,  253,  252,  251,  250,  249,
      248,  247,  246,  244,  240,  239,  238,  237,  235,  234,
      233,  232,  229,  228,  227,  226,  225,  224,  223,  221,
      220,  218,  216,  214,  213,  211,  210,  207,  206,  205,
      204,  203,  202,  201,  199,  198,  197,  196,  194,  193,

      192,  191,  190,  189,  187,  186,  184,  182,  181,  176,
      175,  174,  172,  162,  161,  160,  159,  155,  154,  144,
      143,  142,  141,  139,  137,  136,  134,  133,  132,  129,
      128,  127,  125,  123,  122,  120,  119,  117,  115,  111,
      110,  109,  100,   99,   98,   94,   84,   80,   79,   77,
       75,   72,   68,   67,   66,   58,   52,   50,   49,   48,
       45,   44,   43,   34,   30,   21,   16,   15,   13,    2,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,

      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "gm2/m2.lex"
#define INITIAL 0
#line 2 "gm2/m2.lex"
/* Copyright (C) 2001 Free Software Foundation, Inc.
   This file is part of GNU Modula-2.

GNU Modula-2 is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 2, or (at your option) any later
version.

GNU Modula-2 is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License along
with gm2; see the file COPYING.  If not, write to the Free Software
Foundation, 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include <p2c/p2c.h>

#include "M2Reserved.h"
#include "M2LexBuf.h"

  /*
   *  m2.lex - provides a lexical analyser for GNU Modula-2
   */

  struct lineInfo {
    char            *linebuf;          /* line contents */
    int              linelen;          /* length */
    int              tokenpos;         /* start position of token within line */
    int              toklen;           /* a copy of yylen (length of token) */
    int              nextpos;          /* position after token */
    int              actualline;       /* line number of this line */
    int              inuse;            /* do we need to keep this line info? */
    struct lineInfo *next;
  };

  static int              lineno      =1;   /* a running count of the file line number */
  static char            *filename    =NULL;
  static int              commentLevel=0;
  static struct lineInfo *currentLine=NULL;

        void m2lex_M2Error(const char *);
static  void pushLine     (void);
static  void popLine      (void);
static  void finishedLine (void);
static  void resetpos     (void);
static  void consumeLine  (void);
static  void updatepos    (void);
static  void skippos      (void);
static  void poperrorskip (const char *);
static  void endOfComment (void);
static  void handleDate   (void);
static  void handleLine   (void);
static  void handleFile   (void);

#if !defined(TRUE)
#    define TRUE  (1==1)
#endif
#if !defined(FALSE)
#    define FALSE (1==0)
#endif

#define YY_DECL void yylex (void)
#define COMMENT 1
#define COMMENT1 2
#define LINE0 3
#define LINE1 4
#define LINE2 5


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 71 "gm2/m2.lex"



	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 324 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 471 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 73 "gm2/m2.lex"
{ updatepos();
                             commentLevel=1; pushLine(); skippos(); 
			     BEGIN COMMENT; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 76 "gm2/m2.lex"
{ endOfComment(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 77 "gm2/m2.lex"
{ commentLevel++; pushLine(); updatepos(); skippos(); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 78 "gm2/m2.lex"
{ if (commentLevel == 1) {
                               updatepos();
                               pushLine();
                               skippos();
                               BEGIN COMMENT1;
                             } else
                               updatepos(); skippos();
                           }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 86 "gm2/m2.lex"
{ consumeLine(); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 87 "gm2/m2.lex"
{ updatepos(); skippos(); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 88 "gm2/m2.lex"
{ updatepos(); skippos(); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 89 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_attributeunusedtok); return; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 90 "gm2/m2.lex"
{ updatepos(); skippos(); finishedLine(); BEGIN COMMENT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 91 "gm2/m2.lex"
{ consumeLine(); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 92 "gm2/m2.lex"
{ poperrorskip("unterminated source code directive, missing *>");
                             endOfComment(); }
	YY_BREAK
case YY_STATE_EOF(COMMENT1):
#line 94 "gm2/m2.lex"
{ poperrorskip("unterminated source code directive, missing *>"); BEGIN COMMENT; }
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 95 "gm2/m2.lex"
{ poperrorskip("unterminated comment found at the end of the file, missing *)"); BEGIN INITIAL; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 97 "gm2/m2.lex"
{ consumeLine(); /* printf("found: %s\n", currentLine->linebuf); */ BEGIN LINE0; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 98 "gm2/m2.lex"
{ consumeLine(); /* printf("found: %s\n", currentLine->linebuf); */ BEGIN LINE0; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 99 "gm2/m2.lex"
{ updatepos(); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 100 "gm2/m2.lex"
{ updatepos(); lineno=atoi(yytext)-1; BEGIN LINE1; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 101 "gm2/m2.lex"
{ m2lex_M2Error("missing initial quote after #line directive"); resetpos(); BEGIN INITIAL; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 102 "gm2/m2.lex"

	YY_BREAK
case 18:
YY_RULE_SETUP
#line 103 "gm2/m2.lex"
{ m2lex_M2Error("missing final quote after #line directive"); resetpos(); BEGIN INITIAL; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 104 "gm2/m2.lex"
{ updatepos();
                             filename = (char *)xrealloc(filename, yyleng+1);
			     strcpy(filename, yytext);
                             filename[yyleng-1] = (char)0;  /* remove trailing quote */
                             BEGIN LINE2;
                           }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 110 "gm2/m2.lex"
{ updatepos(); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 111 "gm2/m2.lex"
{ M2LexBuf_SetFile(filename); updatepos(); BEGIN INITIAL; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 112 "gm2/m2.lex"
{ M2LexBuf_PopFile(filename); updatepos(); BEGIN INITIAL; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 113 "gm2/m2.lex"
{ M2LexBuf_PushFile(filename); updatepos(); BEGIN INITIAL; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 115 "gm2/m2.lex"
{ consumeLine(); /* printf("found: %s\n", currentLine->linebuf); */ }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 116 "gm2/m2.lex"
{ consumeLine(); /* printf("found: %s\n", currentLine->linebuf); */ }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 118 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTokCharStar(M2Reserved_stringtok, yytext); return; }
	YY_BREAK
case 27:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 119 "gm2/m2.lex"
{ updatepos();
                             m2lex_M2Error("missing terminating quote, \"");
                             resetpos(); return;
                           }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 124 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTokCharStar(M2Reserved_stringtok, yytext); return; }
	YY_BREAK
case 29:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 125 "gm2/m2.lex"
{ updatepos();
                             m2lex_M2Error("missing terminating quote, '");
                             resetpos(); return;
                           }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(LINE0):
case YY_STATE_EOF(LINE1):
case YY_STATE_EOF(LINE2):
#line 130 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_eoftok); return; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 131 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_plustok); return; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 132 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_minustok); return; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 133 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_timestok); return; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 134 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_dividetok); return; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 135 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_becomestok); return; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 136 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_ambersandtok); return; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 137 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_periodtok); return; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 138 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_commatok); return; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 139 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_semicolontok); return; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 140 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_lparatok); return; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 141 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_rparatok); return; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 142 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_lsbratok); return; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 143 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_rsbratok); return; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 144 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_uparrowtok); return; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 145 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_lcbratok); return; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 146 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_rcbratok); return; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 147 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_singlequotetok); return; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 148 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_equaltok); return; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 149 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_hashtok); return; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 150 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_lesstok); return; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 151 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_greatertok); return; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 152 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_lessgreatertok); return; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 153 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_lessequaltok); return; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 154 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_greaterequaltok); return; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 155 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_periodperiodtok); return; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 156 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_periodperiodperiodtok); return; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 157 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_colontok); return; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 158 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_doublequotestok); return; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 159 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_bartok); return; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 160 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_nottok); return; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 161 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_andtok); return; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 162 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_arraytok); return; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 163 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_begintok); return; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 164 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_bytok); return; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 165 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_casetok); return; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 166 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_consttok); return; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 167 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_definitiontok); return; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 168 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_divtok); return; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 169 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_dotok); return; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 170 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_elsetok); return; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 171 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_elsiftok); return; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 172 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_endtok); return; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 173 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_exittok); return; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 174 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_exporttok); return; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 175 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_fortok); return; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 176 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_fromtok); return; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 177 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_iftok); return; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 178 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_implementationtok); return; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 179 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_importtok); return; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 180 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_intok); return; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 181 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_looptok); return; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 182 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_modtok); return; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 183 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_moduletok); return; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 184 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_nottok); return; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 185 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_oftok); return; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 186 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_ortok); return; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 187 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_pointertok); return; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 188 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_proceduretok); return; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 189 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_qualifiedtok); return; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 190 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_unqualifiedtok); return; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 191 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_recordtok); return; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 192 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_repeattok); return; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 193 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_returntok); return; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 194 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_settok); return; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 195 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_thentok); return; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 196 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_totok); return; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 197 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_typetok); return; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 198 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_untiltok); return; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 199 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_vartok); return; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 200 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_whiletok); return; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 201 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_withtok); return; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 202 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_asmtok); return; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 203 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTok(M2Reserved_volatiletok); return; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 204 "gm2/m2.lex"
{ updatepos(); handleDate(); return; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 205 "gm2/m2.lex"
{ updatepos(); handleLine(); return; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 206 "gm2/m2.lex"
{ updatepos(); handleFile(); return; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 208 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTokCharStar(M2Reserved_realtok, yytext); return; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 209 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTokCharStar(M2Reserved_identtok, yytext); return; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 210 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTokCharStar(M2Reserved_integertok, yytext); return; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 211 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTokCharStar(M2Reserved_integertok, yytext); return; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 212 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTokCharStar(M2Reserved_integertok, yytext); return; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 213 "gm2/m2.lex"
{ updatepos(); M2LexBuf_AddTokCharStar(M2Reserved_integertok, yytext); return; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 214 "gm2/m2.lex"
{ currentLine->tokenpos += yyleng;  /* ignore whitespace */; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 215 "gm2/m2.lex"
{ updatepos(); m2lex_M2Error("unrecognised symbol"); skippos(); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 217 "gm2/m2.lex"
ECHO;
	YY_BREAK

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 324 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 324 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 323);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *)xmalloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *)xrealloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 217 "gm2/m2.lex"


/* have removed the -? from the beginning of the real/integer constant literal rules */

/*
 *  hand built routines
 */

/*
 *  handleFile - handles the __FILE__ construct by wraping it in double quotes and putting
 *               it into the token buffer as a string.
 */

static void handleFile (void)
{
  char *s = (char *)alloca(strlen(filename)+2+1);

  strcpy(s, "\"");
  strcat(s, filename);
  strcat(s, "\"");
  M2LexBuf_AddTokCharStar(M2Reserved_stringtok, s);
}

/*
 *  handleLine - handles the __LINE__ construct by passing an integer to
 *               the token buffer.
 */

static void handleLine (void)
{
  M2LexBuf_AddTokInteger(M2Reserved_integertok, lineno);
}

/*
 *  handleDate - handles the __DATE__ construct by passing the date
 *               as a string to the token buffer.
 */

static void handleDate (void)
{
  time_t  clock = time((long *)0);
  char   *sdate = ctime(&clock);
  char   *s     = (char *)alloca(strlen(sdate)+2+1);
  char   *p     = index(sdate, '\n');

  if (p != NULL) {
    *p = (char) 0;
  }
  strcpy(s, "\"");
  strcat(s, sdate);
  strcat(s, "\"");
  M2LexBuf_AddTokCharStar(M2Reserved_stringtok, s);
}

/*
 *  endOfComment - handles the end of comment
 */

static void endOfComment (void)
{
  commentLevel--;
  updatepos();
  skippos();
  if (commentLevel==0) {
    BEGIN INITIAL;
    finishedLine();
  } else
    popLine();
}

/*
 *  m2lex_M2Error - displays the error message, s, after the code line and pointer
 *                  to the erroneous token.
 */

void m2lex_M2Error (const char *s)
{
  if (currentLine->linebuf != NULL) {
    int i=1;

    printf("%s:%d:%s\n", filename, currentLine->actualline, currentLine->linebuf);
    printf("%s:%d:%*s", filename, currentLine->actualline, 1+currentLine->tokenpos, "^");
    while (i<currentLine->toklen) {
      putchar('^');
      i++;
    }
    putchar('\n');
  }
  printf("%s:%d:%s\n", filename, currentLine->actualline, s);
}

static void poperrorskip (const char *s)
{
  int nextpos =currentLine->nextpos;
  int tokenpos=currentLine->tokenpos;

  popLine();
  m2lex_M2Error(s);
  if (currentLine != NULL) {
    currentLine->nextpos  = nextpos;
    currentLine->tokenpos = tokenpos;
  }
}

/*
 *  consumeLine - reads a line into a buffer, it then pushes back the whole
 *                line except the initial \n.
 */

static void consumeLine (void)
{
  if (currentLine->linelen<yyleng) {
    currentLine->linebuf = (char *)xrealloc(currentLine->linebuf, yyleng);
    currentLine->linelen = yyleng;
  }
  strcpy(currentLine->linebuf, yytext+1);  /* copy all except the initial \n */
  lineno++;
  currentLine->actualline = lineno;
  currentLine->tokenpos=0;
  currentLine->nextpos=0;
  yyless(1);                  /* push back all but the \n */
}

/*
 *  updatepos - updates the current token position.
 *              Should be used when a rule matches a token.
 */

static void updatepos (void)
{
  currentLine->nextpos = currentLine->tokenpos+yyleng;
  currentLine->toklen  = yyleng;
}

/*
 *  skippos - skips over this token. This function should be called
 *            if we are not returning and thus not calling getToken.
 */

static void skippos (void)
{
  currentLine->tokenpos = currentLine->nextpos;
}

/*
 *  initLine - initializes a currentLine
 */

static void initLine (void)
{
  currentLine = (struct lineInfo *)xmalloc(sizeof(struct lineInfo));

  if (currentLine == NULL)
    perror("xmalloc");
  currentLine->linebuf    = NULL;
  currentLine->linelen    = 0;
  currentLine->tokenpos   = 0;
  currentLine->toklen     = 0;
  currentLine->nextpos    = 0;
  currentLine->actualline = lineno;
  currentLine->inuse      = TRUE;
  currentLine->next       = NULL;
}

/*
 *  pushLine - pushes a new line structure.
 */

static void pushLine (void)
{
  if (currentLine == NULL) {
    initLine();
  } else if (currentLine->inuse) {
      struct lineInfo *l = (struct lineInfo *)xmalloc(sizeof(struct lineInfo));

      if (currentLine->linebuf == NULL) {
	l->linebuf  = NULL;
	l->linelen  = 0;
      } else {
	l->linebuf    = (char *)xstrdup(currentLine->linebuf);
	l->linelen    = strlen(l->linebuf)+1;
      }
      l->tokenpos   = currentLine->tokenpos;
      l->toklen     = currentLine->toklen;
      l->nextpos    = currentLine->nextpos;
      l->actualline = currentLine->actualline;
      l->next       = currentLine;
      currentLine   = l;
  }
  currentLine->inuse = TRUE;
}

/*
 *  popLine - pops a line structure.
 */

static void popLine (void)
{
  if (currentLine != NULL) {
    struct lineInfo *l = currentLine;

    if (currentLine->linebuf != NULL)
      free(currentLine->linebuf);
    currentLine = l->next;
    free(l);
  }
}

/*
 *  resetpos - resets the position of the next token to the start of the line.
 */

static void resetpos (void)
{
  if (currentLine != NULL)
    currentLine->nextpos = 0;
}

/*
 *  finishedLine - indicates that the current line does not need to be preserved when a pushLine
 *                 occurs.
 */

static void finishedLine (void)
{
  currentLine->inuse = FALSE;
}

/*
 *  m2lex_GetToken - returns a new token.
 */

char *m2lex_GetToken (void)
{
  if (currentLine == NULL)
    initLine();
  currentLine->tokenpos = currentLine->nextpos;
  yylex();
  return( yytext );
}

/*
 *  CloseSource - provided for semantic sugar
 */

void m2lex_CloseSource (void)
{
}

/*
 *  OpenSource - returns TRUE if file, s, can be opened and
 *               all tokens are taken from this file.
 */

int m2lex_OpenSource (char *s)
{
  FILE *f = fopen(s, "r");

  if (f == NULL)
    return( FALSE );
  else {
    yy_delete_buffer(YY_CURRENT_BUFFER);
    yy_switch_to_buffer(yy_create_buffer(f, YY_BUF_SIZE));
    filename = xstrdup(s);
    lineno   =1;
    return( TRUE );
  }
}

/*
 *  m2lex_GetLineNo - returns the current line number.
 */

int m2lex_GetLineNo (void)
{
  if (currentLine != NULL)
    return currentLine->actualline;
  else
    return 0;
}

/*
 *  yywrap is called when end of file is seen. We push an eof token
 *         and tell the lexical analysis to stop.
 */

int yywrap (void)
{
  updatepos(); M2LexBuf_AddTok(M2Reserved_eoftok); return 1;
}

void _M2_m2lex_init () {}
