IMPLEMENTATION MODULE M2Version ;

FROM StrIO IMPORT WriteString ;


(* Generated by makeversion - do not edit *)

(*
   WriteVersion - writes the current version of the compiler
*)

PROCEDURE WriteVersion ;
BEGIN
    WriteString('0.21b (gaius@isode)') ;
END WriteVersion ;


END M2Version.
