#!/bin/sh

for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 ; do
   echo MAP $i
   if [ -f m$i ] ; then
      ed m$i << EOFEOF >& /dev/null
/ROOM
i
  
.
.-1
1,.d
w
q
EOFEOF
      semantic m$i
   fi
done
semantic ty-nant
